---
title: "Backup R PCA Analysis"
author: "Alicia McElwee"
date: "12/15/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This analysis was done to supplement the fact that I could not get enrichment analysis to work in the ParTI program. I did a simple PCA loading analysis using the prcomp R function to understand which general genomic feature values may be trading off with each other and so may be of interest when defining microbial life history strategies.


```{r libraries}
library(readr)
library(ggplot2)
library(readxl)
library(devtools)
library(ggbiplot)
library(rgl)
```


```{r data_loading}

log_feature_values = read_xlsx("LOGTranform_NEWGenomeNEWFeaturevalues.xlsx")
log_feature_values_num_only = log_feature_values[,-1]

```


```{r pca}
pc <- prcomp(log_feature_values[,-1],
             center = TRUE,
            scale. = TRUE)
attributes(pc)

```


```{r biplot}
library(devtools)
#install_github("vqv/ggbiplot")
library(ggbiplot)
g <- ggbiplot(pc,
              obs.scale = 1,
              var.scale = 1,
              varnam.size = 0.05)
g <- g + scale_color_discrete(name = '')
g <- g + theme(legend.direction = 'horizontal',
               legend.position = 'top')
g <- g + xlim(-15,15) + ylim(-10, 15)
print(g)

```

```{r 3D_biplot}
scores = as.data.frame(pc$x)

plot3d(scores[,1:3])
 
 
text3d(pc$rotation[,1:3], 
       texts=rownames(pc$rotation), 
       col="red", 
       cex=1)
 
coords <- NULL
for (i in 1:nrow(pc$rotation)) {
  coords <- rbind(coords, 
                  rbind(c(0,0,0),
                                pc$rotation[i,1:3]))
}
 
lines3d(coords, 
        col="red", 
        lwd=4)

# I did not include this plot in the report as it did not show up well in a 2D rendering and required a lot of zooming in and moving around to make sense of the loading values.
```
